---
- name: Create ~/bin folder
  file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory

- name: Add extractrpm
  copy:
    src: scripts/extractrpm
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755
