---
# Dotfiles
- name: ssh directory
  file:
    path: "{{ ansible_user_dir }}/.ssh/"
    state: directory
    mode: 0700

- name: Config directories
  file:
    path: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
  with_items:
    - terminator
    - powerline

- name: Powerline config
  copy:
    src: powerline/config.json
    dest: "{{ ansible_user_dir }}/.config/powerline/config.json"

- name: Terminator config
  copy:
    src: terminator/config
    dest: "{{ ansible_user_dir }}/.config/terminator/config"

- name: vimrc
  copy:
    src: vim/.vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"

- name: Bash customizations
  copy:
    src: bash/{{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - { src: '.bashrc', dest: '{{ ansible_user_dir }}/.bashrc' }
    - { src: '.bash_logout', dest: '{{ ansible_user_dir }}/.bash_logout' }
    - { src: '.bash_profile', dest: '{{ ansible_user_dir }}/.bash_profile' }
