---
# Bluejeans
- name: Get last bluejeans version
  shell: "curl -s https://www.bluejeans.com/downloads#desktop | grep -o -E 'href=\"([^\"#]+)\"'| cut -d'\"' -f2 | grep 'rpm$'"
  register: bluejeansurl

- name: Install Bluejeans
  dnf:
    name: "{{ bluejeansurl.stdout }}"
    state: present
  become: true
